services:
  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ${fsTracker}:/app/fsTracker
      - ${fromFsTracker}:/app/fromFsTracker
      - ./log:/app/log

  db:
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5436:5436"
    command:
      - -p 5436
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres -p 5436" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/database/copyHhFromParser:/var/lib/postgresql/data
