services:
  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ${fsTracker}:/app/fsTracker
      - ${fromFsTracker}:/app/fromFsTracker
      - ./log:/app/log
    networks:
      - copyHhFromParser-network

  db:
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres -p 5432" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - copyHhFromParser-network

volumes:
  postgres:

networks:
  copyHhFromParser-network:

