services:
  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - C:\\FStracker:/app/FStracker
      - C:\\FromFStracker:/app/FromFStracker

  db:
    image: postgres:12
    restart: always
    ports:
      - "5436:5436"
    command:
      - -p 5436
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - C:\\Program Files\\PostgreSQL\\docker\\copyHHFromParser:/var/lib/postgresql/data
