services:
  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - C:\\FStracker:/app/FStracker
      - C:\\FromFStracker:/app/FromFStracker

  db:
    image: postgres:12
    restart: always
    ports:
      - "5433:5433"
    command:
      - -p 5433
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      #      - ./resources/init.sql:/docker-entrypoint-initdb.d
      - C:\\Program Files\\PostgreSQL\\12\\data:/var/lib/postgresql/data
