services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dbpass
      PATH_TO_FSTRACKER: /app/fstracker
      PATH_TO_PROCESSED: /app/processed
    volumes:
      - C:\\FStracker:/app/fstracker
      - C:\\Users\user\AppData\Local\PokerTracker 4\Processed\:/app/processed

  db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
